name: Testery Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Testery CLI
        run: |
          python -m pip install --upgrade pip
          pip install testery --upgrade
      - name: Run Testery tests
        run: |
          echo "git-ref: ${{github.event.pull_request.head.sha}} branch: ${{ github.event.pull_request.head.ref }}"

          testery create-test-run \
            --testery-dev \
            --token "${{ secrets.TESTERY_TOKEN }}" \
            --git-ref "${{github.event.pull_request.head.sha}}" \
            --git-branch "${{ github.event.pull_request.head.ref }}" \
            --project "example-cypress-cucumber-10" \
            --environment "development" \
            --apply-test-selection-rules
