name: Testery Tests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # env:
    #   TESTERY_TOKEN: ${{ secrets.TesteryTokenProd }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install Testery CLI
        run: |
          python -m pip install --upgrade pip
          pip install testery --upgrade
      - name: Run Testery tests
        run: |
          testery create-test-run \
              --token "${{ secrets.TESTERY_TOKEN }}" \
              --git-ref "${{github.event.pull_request.head.sha}}" \
              --project "example-cypress-cucumber-10" \
              --environment "testery-dev" \
              --test-suite "Green"
